### PR TITLE
Merge from s4m

### PR DESCRIPTION
**Pull request by tingxuanz**
axis.js, features.js, general.js is updated to the same version as Stemformatics

update options in 1_sample_small.js

### CODE REVIEW

**Comment by rowlandm** [comment]
I don't think we should be merging pull requests straight into master.

Peter - can you do a pull request into another branch? ie ArianeMora:mergeFromS4m?

Is that possible?

**Comment by tingxuanz** [comment]
I think Ariane needs to create a branch called mergeFromS4m. Then I can send a pull request to that branch.

Or I can send a pull request to another branch which already exists, ie merging-isha-code. Master branch and merging-isha-code branch are identical.

**Comment by rowlandm** [comment]
Hi all,

I think Ariane can create a branch on the fly when she accepts the pull
request. I can't remember.

**Comment by ArianeMora** [comment]
Hi Peter, 

I've merged your code to the mergeFromS4m branch.

Cheers!

**Pull request closed without merging**
